# Generated by Django 5.2.7 on 2025-10-03 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The main title of the post.', max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, help_text='Automatically generated slug from the title for URLs.', max_length=255, unique=True)),
                ('content', models.TextField(help_text='The full body content of the post. Supports Markdown/HTML.')),
                ('summary', models.TextField(blank=True, help_text='A short summary/excerpt shown on listing pages.', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='The current publishing status.', max_length=10)),
                ('is_featured', models.BooleanField(default=False, help_text='Designates if the post should be featured on the homepage.')),
                ('image', models.ImageField(blank=True, help_text='Optional header image for the post.', null=True, upload_to='post_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the post was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last modification.')),
                ('published_date', models.DateTimeField(blank=True, help_text='The date and time the post was actually published.', null=True)),
                ('author', models.ForeignKey(help_text='The user who created the post.', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='The primary category of the post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category')),
                ('tags', models.ManyToManyField(blank=True, help_text='A list of tags associated with the post.', related_name='posts', to='blog.tag')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_date', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status', 'draft'), ('published_date__isnull', False), _connector='OR'), name='published_posts_must_have_published_date')],
            },
        ),
    ]
