# Generated by Django 5.2.7 on 2025-10-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional header image for the post.', null=True, upload_to='blog/post_images/'),
        ),
    ]
